version: '2'
services:
  athenaeum:
    build: .
    volumes:
      - ./styleguide:/app/styleguide
      - .:/go/src/github.com/buildkite/agent
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
      - ./coverage:/app/coverage
    command: yarn run build
    environment:
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN=$BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_NUMBER
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NPM_USERNAME
      - NPM_PASSWORD
      - NPM_TOKEN
      - NPM_EMAIL
      - GITHUB_TOKEN
      - SONAR_LOGIN
  sonar:
    image: us.gcr.io/pg-shared-v1/sonar-scanner:latest
    volumes:
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
      - ./bin/scan-pullrequest:/usr/bin/scan-pullrequest
      - ./sonar-project.properties:/opt/sonar-scanner/conf/sonar-scanner.properties
      - ./src:/app/src
    command: bin/sonar
    environment:
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN=$BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_NUMBER
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NPM_USERNAME
      - NPM_PASSWORD
      - NPM_TOKEN
      - NPM_EMAIL
      - GITHUB_TOKEN
      - SONAR_LOGIN
