version: '2'
services:
  athenaeum:
    build: .
    volumes:
      - ./styleguide:/app/styleguide
      - .:/go/src/github.com/buildkite/agent
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    command: yarn run build
    environment:
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN=$BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_NUMBER
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NPM_TOKEN
  athenaeum-sonar:
    image: sonarsource/sonar-scanner-cli
    working_dir: /app
    volumes:
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
      - /app/coverage:/app/coverage
      - ./:/app
      - .:/go/src/github.com/buildkite/agent
    environment:
      - BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN=$BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_PULL_REQUEST_BASE_BRANCH
      - BUILDKITE_REPO
      - GITHUB_TOKEN
      - SONAR_LOGIN
  athenaeum-semgrep:
    build:
      context: .
      dockerfile: Dockerfile.semgrep
    shm_size: 512M
    environment:
      - SEMGREP_TOKEN
