---
steps:
  - name: ':docker: Build'
    agents:
      queue: builder
    plugins:
      docker-compose:
        build: athenaeum
        image-repository: quay.io/policygenius/athenaeum

  - wait

  - name: ':rubocop: :scsslint:'
    command: bin/pre_test
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum

  - block: 'Bump the version'
    prompt: 'How big do you want it?'
    # branches: 'master'
    fields:
    - select: 'Increment'
      key: 'bump-size'
      hint: "MAJOR: incompatible API changes // MINOR: add backwards-compatible functionality // PATCH: backwards-compatible bug fixes"
      required: true
      options:
        - label: 'Major'
          value: 'major'
        - label: 'Minor'
          value: 'minor'
        - label: 'Patch'
          value: 'patch'

  - wait

  - name: ':rocket: Deploy'
    command: bin/deploy
    # branches: master
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum

  - wait

  - name: ':rocket: Commit tag'
    command: bin/commit-tag
    # branches: master
    agents:
      queue: builder
